### ISSUE TITLE
auro-radio: slots for label children

### ISSUE THREAD

**Issue by Dayna-A** [AlaskaAirlines/auro-radio#31] opened 2021-05-18 23:35 UTC
## Is your feature request related to a problem? Please describe.!
It is not possible to add child elements to each radio-button label. This means that I am unable to implement a design which displays a header and details of Lounge Membership Options using an auro-radio-button.

## Describe the solution you'd like
I would like to have a slot available to me for each radio button label, to allow me to add child elements with all the details needed for that option.

## Describe alternatives you've considered
Alternatively, I can build my own solution to the design using standard html radio inputs, with individual blocks to display and label the necessary headings and details for that input.

## Additional context
This is the design I am trying to implement with auro-radio-buttons for selling multiple levels of lounge membership.
[image](https://user-images.githubusercontent.com/35708093/118735918-9c7dd300-b7fe-11eb-8fff-6ba5b8860905.png)

**Comment by blackfalcon** [comment] 2021-05-19 13:33
The fork in the road depends on the opportunities available. Ideally, we would love to have this be part of the Auro API, but that depends on the time available. Do we have support from design to vet this idea for repeatability with the radio and checkbox components and work on a developed response? 

If not, then the other option is to build a local one-off solution with the hope that it will be retrofitted with the updates component.

**Comment by zzacal** [comment] 2021-05-19 16:44
The ability to add children would also help us with this design:
![email component](https://user-images.githubusercontent.com/54555150/118851534-b9f67f80-b886-11eb-8127-4cf4ad688902.png)

We would probably need help with the designers to figure out where the button lines up.

**Comment by blackfalcon** [comment] 2021-06-11 20:11
This issue is a dupe of https://github.com/AlaskaAirlines/auro-radio/issues/40

@zzacal the image you posted is in re-review with design and will not be part of the https://github.com/AlaskaAirlines/auro-radio/issues/40 scope. Look for updates post design review.

**Closed by blackfalcon** 2021-06-11 20:11 UTC
Labels: Type: Feature, duplicate

**Comment by zzacal** [comment] 2021-06-11 22:04
@blackfalcon the image I posted, is outdated. I'll mark it as such.
